import { Player, UserCard } from '@/types/game';

export const MOCK_PLAYERS: Player[] = [
  {
    id: '1',
    name: 'Vinícius Júnior',
    country: 'Brasil',
    position: 'ATA',
    number: 7,
    overall: 92,
    rarity: 'mythic',
    stats: { attack: 95, defense: 30, speed: 97, pass: 85, dribble: 98, physical: 70 },
    image_url: 'https://img.asmedia.epimg.net/resizer/v2/W5DMB7T7MZLTVK6W6Y6W6Y6W6Y.jpg?auth=8f7e3d8f7e3d8f7e3d8f7e3d8f7e3d8f7e3d8f7e3d8f7e3d8f7e3d8f7e3d8f7e&width=1200&height=1200&smart=true',
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Lionel Messi',
    country: 'Argentina',
    position: 'ATA',
    number: 10,
    overall: 91,
    rarity: 'legendary',
    stats: { attack: 91, defense: 25, speed: 82, pass: 95, dribble: 96, physical: 65 },
    image_url: 'https://images.psg.media/media/1/Players/Messi/Portrait-Messi-2022.png',
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Kylian Mbappé',
    country: 'França',
    position: 'ATA',
    number: 10,
    overall: 92,
    rarity: 'legendary',
    stats: { attack: 94, defense: 35, speed: 98, pass: 82, dribble: 93, physical: 78 },
    image_url: 'https://images.psg.media/media/1/Players/Mbappe/Portrait-Mbappe-2022.png',
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Jude Bellingham',
    country: 'Inglaterra',
    position: 'MEI',
    number: 5,
    overall: 89,
    rarity: 'epic',
    stats: { attack: 85, defense: 78, speed: 84, pass: 88, dribble: 88, physical: 85 },
    image_url: 'https://publish-p47754-e237307.adobeaemcloud.com/content/dam/rmp/legacy-assets/players/jude-bellingham/jude-bellingham.png',
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Lamine Yamal',
    country: 'Espanha',
    position: 'ATA',
    number: 19,
    overall: 82,
    rarity: 'rare',
    stats: { attack: 80, defense: 20, speed: 88, pass: 78, dribble: 90, physical: 55 },
    image_url: 'https://www.fcbarcelona.com/fcbarcelona/photo/2023/07/11/7f3a8b3d-1b3a-4b3a-8b3a-4b3a8b3a4b3a/Lamine-Yamal.png',
    created_at: new Date().toISOString(),
  }
];

export const MOCK_USER_CARDS: UserCard[] = [
  {
    id: 'u1',
    user_id: 'user_1',
    player_id: '1',
    is_shiny: true,
    is_locked: false,
    is_golden: true,
    is_pasted: false,
    quantity: 30,
    acquired_at: new Date().toISOString(),
  },
  {
    id: 'u2',
    user_id: 'user_1',
    player_id: '2',
    is_shiny: false,
    is_locked: false,
    is_golden: false,
    is_pasted: false,
    quantity: 1,
    acquired_at: new Date().toISOString(),
  },
  {
    id: 'u3',
    user_id: 'user_1',
    player_id: '3',
    is_shiny: false,
    is_locked: false,
    is_golden: false,
    is_pasted: false,
    quantity: 1,
    acquired_at: new Date().toISOString(),
  }
];

export const MOCK_USER_PROFILE = {
  id: 'user_1',
  username: 'Caio',
  avatar_url: '',
  level: 15,
  xp: 1200,
  coins: 12500,
  gems: 450,
  is_vip: true,
  created_at: new Date().toISOString(),
};
